### ISSUE TITLE
TDP Wrong for Ayaneo Geek

### ISSUE THREAD

**Issue by furbyhaxx** [hhd-dev/adjustor#11]
Hi

I noticed that the TDP are wrongly set for the Ayaneo Geek.
First I disabled the /sys mount for steam, then if I set the TDP to 25W without boost, it's effectively 35.
If it's set to 15 it's effectively 25.

Looks like the GPU clock is not set correctly, because if I limit it manually the TDP are going down.

Did not had time to get used to the source of hhd and adjustor to fix it myself, especially with adjustor and the whole power stuff.

**Comment by antheas** [comment]
Total power consumption or TDP? Because total power consumption on ayaneo at 15W is 25W

**Comment by furbyhaxx** [comment]
Total, looks like I am missunderstanding TDP...
Because I expected to limit the max power consumption

**Comment by furbyhaxx** [comment]
misunderstanding of the mechanics
