### ISSUE TITLE
8840U support

### ISSUE THREAD

**Issue by nemanjan00** [hhd-dev/adjustor#3]
Hello,
I saw you have added support for 8840U (Win Max 2 2024) but there was no release since then. 

Is it safe to use or is it still experimental?

Can you confirm if it works?

Thanks for amazing work!

**Comment by antheas** [comment]
Hi. I checked out the ACPI implementation of 8th gen and it turns out it has not changed at all.

However, the person who gave me the ACPI data did not test if it actually works. Since most people use decky plugins for TDP 

It should be safe. If you test and give the OK I will queue a release today.

**Comment by nemanjan00** [comment]
Yeah, I can test it. 

I just need a bit of help with how do I confirm it is working. What tool do I use to read power consumption? lm_sensors?

**Comment by antheas** [comment]
`watch -n 0.1 sensors` while you're doing something intense such as Geekbench, unigine benchmark or a game. Look at avg ppt

**Comment by antheas** [comment]
Do not expect it to match below 8w. Seems the minimum under load is around 7w.

**Comment by nemanjan00** [comment]
Just adding this line:

https://github.com/hhd-dev/adjustor/blob/main/src/adjustor/core/const.py#L56

Looks like it mostly works (I set limit at 4W, it sometimes peaks up to 5W, I set limit at 30W, it does peak at 25W and above for short periods)

**Comment by nemanjan00** [comment]
I can later test whole code, if there is anything else changed, that might cause issues

**Comment by antheas** [comment]
Just mind the fact that 30w is a generic limit

Depending on the configuration of your device it might be bios limited.

TDPs between 8w and 25w work correctly?

**Comment by nemanjan00** [comment]
It does seem to overshoot limit, but, by similar value, for all settings I have tried

**Comment by antheas** [comment]
If you want to test the exact limit, disable TDP boost. Otherwise it is going to overshoot by a similar amount until the device is thermally saturated.

**Comment by nemanjan00** [comment]
Yeah, this looks precise enough, at least for my use

**Comment by nemanjan00** [comment]
Thanks
