### ISSUE TITLE
Asus Charging Limit takes 1 second to write / needs to be debounced

### ISSUE THREAD

**Issue by 522122** [hhd-dev/adjustor#6]
Noticed server responses are kind of slow. Polling takes 2 sec and applying setting around 1 sec. This feels sometimes slow, especially when updating the sliders with controller. Every step you get 1 sec "lag"

Device: Rog Ally X, running UI on mac in dev

<img width="1349" alt="Screenshot 2024-08-13 at 11 55 42" src="https://github.com/user-attachments/assets/295028cb-9f91-4794-88d0-791ff0fca99b">

**Comment by antheas** [comment]
https://github.com/hhd-dev/adjustor/releases/tag/v3.4.6

Wow a month on the dot. Debouncing it worked
